# Generated by Django 4.2.20 on 2025-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='书名')),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ISBN')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '借出'), (3, '销毁')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'books',
                'verbose_name_plural': 'books',
                'db_table': 'books',
            },
        ),
    ]
