# Generated by Django 4.2.20 on 2025-04-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借出时间')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('last_reminder', models.DateField(blank=True, null=True, verbose_name='系统提醒时间')),
                ('status', models.IntegerField(choices=[(1, '借出'), (2, '归还')], default=1, verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': 'book_record',
                'verbose_name_plural': 'book_record',
                'db_table': 'book_record',
            },
        ),
    ]
