# Generated by Django 4.2.20 on 2025-04-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookrecord',
            index=models.Index(fields=['borrow_date', 'due_date'], name='book_record_borrow__d9d3aa_idx'),
        ),
    ]
